// <auto-generated />
using FilterHomeWork.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FilterHomeWork.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20210304162911_Create tblFilterNameValuesHW1")]
    partial class CreatetblFilterNameValuesHW1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("FilterHomeWork.Entities.FilterName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("tblFilterNameHW1");
                });

            modelBuilder.Entity("FilterHomeWork.Entities.FilterNameValue", b =>
                {
                    b.Property<int>("FilterNameId")
                        .HasColumnType("integer");

                    b.Property<int>("FilterValueId")
                        .HasColumnType("integer");

                    b.HasKey("FilterNameId", "FilterValueId");

                    b.HasIndex("FilterValueId");

                    b.ToTable("tblFilterNameValuesHW1");
                });

            modelBuilder.Entity("FilterHomeWork.Entities.FilterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("tblFilterValuesHW1");
                });

            modelBuilder.Entity("FilterHomeWork.Entities.FilterNameValue", b =>
                {
                    b.HasOne("FilterHomeWork.Entities.FilterName", "FilterName")
                        .WithMany("NameValues")
                        .HasForeignKey("FilterNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilterHomeWork.Entities.FilterValue", "FilterValue")
                        .WithMany("NameValues")
                        .HasForeignKey("FilterValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterName");

                    b.Navigation("FilterValue");
                });

            modelBuilder.Entity("FilterHomeWork.Entities.FilterName", b =>
                {
                    b.Navigation("NameValues");
                });

            modelBuilder.Entity("FilterHomeWork.Entities.FilterValue", b =>
                {
                    b.Navigation("NameValues");
                });
#pragma warning restore 612, 618
        }
    }
}
